name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
    paths:
      - "**/*"
      - "!functions/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: |
          export NEXT_PUBLIC_API_URL=https://us-central1-idh-mex.cloudfunctions.net
          yarn install --frozen-lockfile  # Instala dependencias utilizando el caché si está disponible
          yarn build  # Construye el proyecto

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IDH_MEX }}
          channelId: live
          projectId: idh-mex
